spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/football_manager
    username: root
    password: 956034

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    validate-on-migrate: true